social/dwitter/urls.py
from django.urls import path, include
from .views import dashboard, profile_list, profile, register
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy


app_name = "dwitter"

urlpatterns = [
    path("",dashboard, name="dashboard"),
    path("profile_list/", profile_list, name="profile_list"),
    path("profile/<int:pk>", profile, name="profile"),
    path("accounts/", include("django.contrib.auth.urls")),
    path("register/", register, name="register"),
    
    # change/reset password don't work, except when I added them explicitly here
    path(
        'password_change/',
        auth_views.PasswordChangeView.as_view(
            success_url=reverse_lazy("dwitter:password_change_done")),
        name="password_change"),
    path(
        'password_reset/',
        auth_views.PasswordResetView.as_view(
            success_url=reverse_lazy("dwitter:password_reset_done")),
        name="password_reset"),    
]

social/social/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include("dwitter.urls")),
    
    #password_reset_confirm works when i put the path here
    path(
        'password_reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            success_url=reverse_lazy('dwitter:password_reset_complete')),
        name="password_reset_confirm",
    ),
    # need to rewrite the password_reset path here if I want to put an email that is not in the database
]

social/dwitter/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    follows = models.ManyToManyField(
        "self",
        related_name="followed_by",
        symmetrical=False,#user do not need to re follow 
        blank=True,#the user can have empty follower
        )
    def __str__(self):
        return self.user.username
    
#signal to create profile for every user created 
@receiver(post_save, sender=User)# instead of post_save.connect
def create_profile(sender, instance, created, **kwargs):
    if created:
        user_profile = Profile(user=instance)
        user_profile.save()
        user_profile.follows.set([instance.profile.id])#to make the user follow himself
        user_profile.save()
      
class Dweet(models.Model):
    user = models.ForeignKey(User, related_name="dweets", on_delete=models.DO_NOTHING)#related_name:to access the dweets from the user
    body = models.CharField(max_length=140)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return (f"{self.user} "
                f"({self.created_at:%Y-%m-%d %H:%M}): "
                f"{self.body[:30]}...")

social/dwitter/forms.py
from django import forms
from .models import Dweet
from django.contrib.auth.forms import UserCreationForm

class DweetForm(forms.ModelForm):
    body = forms.CharField(
        required=True,
        widget=forms.widgets.Textarea(
            attrs={"placeholder": "Dweet something...",
                   "class": "textarea is-success is-medium",}),
        label="",)
    class Meta:
        model = Dweet
        exclude = ("user", )
        
class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = UserCreationForm.Meta.fields + ("email",)

social/dwitter/views.py
from django.shortcuts import render,redirect
from .models import Profile,Dweet
from .forms import DweetForm,CustomUserCreationForm
from django.contrib.auth import login
from django.urls import reverse

def dashboard(request):
    if request.user.is_authenticated :
        
        form = DweetForm(request.POST or None)
        if request.method == "POST":
            # form = DweetForm(request.POST)#fill the form to the new data 
            if form.is_valid():
                dweet = form.save(commit=False)
                dweet.user = request.user#get the user who added the dweet
                dweet.save()
                return redirect("dwitter:dashboard")#GET
        followed_dweets = Dweet.objects.filter(
            user__profile__in=request.user.profile.follows.all()).order_by("-created_at")
        return render(request, "dwitter/dashboard.html", {"form": form,"dweets":followed_dweets})
    
    else:
        return redirect("dwitter:login")
        

def profile_list(request):
    profiles = Profile.objects.exclude(user=request.user)
    return render(request,"dwitter/profile_list.html",{"profiles": profiles})

def profile(request,pk):
    #if the user has no profile
    if not hasattr(request.user, 'profile'):
        missing_profile = Profile(user=request.user)
        missing_profile.save()
        
    profile=Profile.objects.get(pk=pk)
    if request.method == "POST":
        current_user_profile = request.user.profile
        data = request.POST#get the data from the request
        action = data.get("follow")#get the value of the attribute named follow
        if action == "follow":
            current_user_profile.follows.add(profile)
        elif action == "unfollow":
            current_user_profile.follows.remove(profile)
        current_user_profile.save()
    return render(request,"dwitter/profile.html",{"profile":profile})

def register(request):
    if request.method == "GET":
        return render(
            request, "dwitter/register.html",
            {"form": CustomUserCreationForm})
        
    elif request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
        return redirect(reverse("dwitter:dashboard"))

social/dwitter/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Include the Bulma CSS framework for styling -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <title>Dwitter</title>
</head>

<body>
    <section class="hero is-small is-success mb-4">
        <div class="hero-body">
            <h1 class="title is-1">Dwitter</h1>
            <p class="subtitle is-4">
                Your tiny social network built with Django
            </p>
            {% if user.is_authenticated %}
                <a href="{% url 'dwitter:dashboard' %}">HomePage |</a>
                <a href="{% url 'dwitter:profile' user.profile.id %}">your profile |</a>
                <a href="{% url 'dwitter:password_change' %}">Change password |</a>
                <a href="{% url 'dwitter:logout'%}">Logout</a>
            {%endif%}
        </div>

    </section>
    <div class="container">
        <div class="columns">
            {% block content %}
            {% endblock content %}
        </div>
    </div>
    
</body>

</html>

social/dwitter/templates/dwitter/dashboard.html
{% extends 'base.html' %}
{% block content %}
<div class="column">
    {% for dweet in dweets %}
    <div class="box">
        {{ dweet.body }}
        <span class="is-small has-text-grey-light">
            ({{ dweet.created_at }} by {{ dweet.user.username }})
        </span>
    </div>
    {% endfor %}
</div>

<div class="column is-one-third">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="button is-success is-fullwidth is-medium mt-5" type="submit">Dweet</button>
    </form>
</div>
{% endblock %}

social/dwitter/templates/dwitter/profile.html
{% extends 'base.html' %}
{% block content %}
<div class="column">
    <div class="block">
        <h1 class="title is-1">
            {{profile.user.username|upper}}'s Dweets
        </h1>
    </div>
    <form method="post">
        {% csrf_token %}
        <div class="buttons has-addons">
            {% if profile in user.profile.follows.all %}
            <button class="button is-success is-static">Follow</button>
            <button class="button is-danger" name="follow" value="unfollow">Unfollow</button>
            {% else %}
            <button class="button is-success" name="follow" value="follow">Follow</button>
            <button class="button is-danger is-static">Unfollow</button>
            {% endif %}
        </div>
    </form>
    <div class="content">
        {% for dweet in profile.user.dweets.all %}
        <div class="box">
            {{ dweet.body }}
            <span class="is-small has-text-grey-light">
                ({{ dweet.created_at }})
            </span>
        </div>
        {% endfor %}
    </div>
</div>

<div class="column is-one-third">
    <div class="block">
        <a href="{% url 'dwitter:profile_list' %}">
            <button class="button is-dark is-outlined is-fullwidth">
                All Profiles
            </button>
        </a>
    </div>
    <div class="block">
        <h3 class="title is-4">
            {{profile.user.username}} follows:
        </h3>
        <div class="content">
            <ul>
                {% for following in profile.follows.all %}
                <li>
                    <a href="{% url 'dwitter:profile' following.id %}">
                        {{ following }}
                    </a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <div class="block">
        <h3 class="title is-4">
            {{profile.user.username}} is followed by:
        </h3>
        <div class="content">
            <ul>
                {% for follower in profile.followed_by.all %}
                <li>
                    <a href="{% url 'dwitter:profile' follower.id %}">
                        {{ follower }}
                    </a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock content %}

social/dwitter/templates/dwitter/profile_list.html
{% extends 'base.html' %}
{% block content %}
<div class="column">
    {% for profile in profiles %}
    <div class="block">
        <div class="card">
            <a href="{% url 'dwitter:profile' profile.id %}">
                <div class="card-content">
                    <div class="media">
                        <div class="media-left">
                            <figure class="image is-48x48">
                                <img src="https://bulma.io/images/placeholders/96x96.png" alt="Placeholder image">
                            </figure>
                        </div>
                        <div class="media-content">
                            <p class="title is-4">
                                {{ profile.user.username }}
                            </p>
                            <p class="subtitle is-6">
                                @{{ profile.user.username|lower }}
                            </p>
                        </div>
                    </div>
                </div>
            </a>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}

social/dwitter/templates/dwitter/register.html
{% extends 'base.html' %}
{% block content %}
<div>
    <h2>Register</h2>
    <br>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Register">
    </form>
    <br>
    <a href="{% url 'dwitter:login' %}">Back to login</a>
</div>
{% endblock %}